language: android
jdk: oraclejdk8
#dist: trusty
env:
  global:
    - ANDROID_API_LEVEL=29
    - ANDROID_BUILD_TOOLS_VERSION=29.0.3
android:
  components:
    - tools
    - platform-tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - sys-img-x86-android-$ANDROID_API_LEVEL
#    - sys-img-armeabi-v7a-android-17

script:
  - ./gradlew clean build
#  - ./gradlew test


before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager “build-tools;29.0.3”


licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
